---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: ネットアップは、製品やサービスの改善と強化を継続的に行っています。最新バージョンの Astra Trident の機能、拡張機能、バグ修正の一部を以下に示します。 
---
= リリースノート
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


リリースノートでは、最新バージョンの Astra Trident の新機能、拡張機能、およびバグ修正に関する情報を提供しています。


WARNING: 。 `tridentctl` インストーラzipファイルに含まれているLinux用のバイナリは、テスト済みでサポートされているバージョンです。に注意してください `macos` バイナリはで提供されます `/extras` zipファイルの一部はテストされていないか、サポートされていません。



== 新機能

ネットアップは、製品やサービスの改善と強化を継続的に行っています。Astra Trident の最新機能を以下に示します。



=== Astra Trident 21.07.02

* XFS ボリュームのクローンをソースボリュームと同じノードにマウントできない固定問題です。




==== 拡張機能

* Kubernetes 1.22 のサポートが追加されました。
* Trident の operator と Helm チャートを Kubernetes 1.22 で使用できるようにしました。


を参照してください https://github.com/NetApp/trident/releases["Astra Trident GitHub"^] を参照してください。



=== Astra Trident 21.07.01

* 画像が異なる固定カスタム YAML インストーラ問題。
* スナップショット・サイズの固定計算問題。


を参照してください https://github.com/NetApp/trident/releases/tag/v21.07.1["Astra Trident GitHub"^] を参照してください。



=== Astra Trident 21.07

Astra Trident 21.07.0 は * ダウンロードできません * 。に変更が加えられました `snapshotReserve` バージョン21.07.0ではCSIになる可能性があります `VolumeSnapshots` PersistentVolumeClaimの作成に使用できない。

バージョン21.07.0にアップグレード済みの場合は、新しく作成したを削除することをお勧めします `VolumeSnapshots` （バージョン21.07.0でプロビジョニング）および以前のリリースへのダウングレード。

を参照してください https://github.com/NetApp/trident/releases/tag/v21.07.0["Astra Trident GitHub"^] を参照してください。



== 既知の問題

ここでは、本製品の正常な使用を妨げる可能性のある既知の問題について記載します。

* Astra Tridentでは空白が強制されるようになりました `fsType` (`fsType=""`）を含むボリューム `fsType` ストレージクラスで指定されています。Tridentでは、Kubernetes 1.17以降を使用している場合は空白の入力がサポートされます `fsType` NFSボリューム。iSCSIボリュームの場合、を設定する必要があります `fsType` ストレージクラスで、を適用する場合 `fsGroup` セキュリティコンテキストの使用。
* 複数のAstra Tridentインスタンスでバックエンドを使用する場合は、各バックエンド構成ファイルに異なる値を設定する必要があります `storagePrefix` ONTAP バックエンドの値を指定するか、別のを使用します `TenantName` SolidFire バックエンドの場合：Astra Trident は、 Astra Trident の他のインスタンスが作成したボリュームを検出できません。ONTAP または SolidFire バックエンドに既存のボリュームを作成しようとすると成功します。 Astra Trident は、ボリューム作成をべき等の操作として扱います。状況 `storagePrefix` または `TenantName` 同じバックエンドに作成されたボリュームでは名前が競合する可能性があるため、同じ名前を変更しないでください。
* Astra Tridentのインストール時（を使用 `tridentctl` またはTrident Operator）を使用し、を使用します `tridentctl` Astra Tridentを管理するには、が次の条件を満たしている必要があります `KUBECONFIG` 環境変数が設定されています。これは、Kubernetesクラスタにそれを示すために必要です `tridentctl` 対策を検討してください。複数のKubernetes環境を使用する場合は、を確認してください `KUBECONFIG` ファイルは正確に取得されます。
* iSCSI PVS のオンラインスペース再生を実行するには、作業者ノード上の基盤となる OS がボリュームにマウントオプションを渡す必要があります。これは、が必要なRHEL / RedHat CoreOSインスタンスに該当します `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["マウントオプション"^]; discard mountOption がに含まれていることを確認します[`StorageClass`^]をクリックして、オンラインブロックの破棄をサポートします。
* Kubernetes クラスタごとに複数の Astra Trident インスタンスがある場合、 Astra Trident は他のインスタンスと通信できず、作成した他のボリュームを検出できません。そのため、 1 つのクラスタ内で複数のインスタンスを実行している場合、予期しない動作が発生したり、誤ったりすることがあります。Kubernetes クラスタごとに Trident のインスタンスが 1 つだけ必要です。
* If Astra Tridentベース `StorageClass` TridentがオフラインのときにKubernetesからオブジェクトが削除されると、対応するストレージクラスがオンラインに戻ってもTridentから削除されることはありません。これらのストレージクラスは、を使用して削除してください `tridentctl` またはREST API。
* 対応する PVC を削除する前に Astra Trident によってプロビジョニングされた PV を削除しても、 Astra Trident は自動的に元のボリュームを削除しません。ボリュームは、から削除する必要があります `tridentctl` またはREST API。
* FlexGroup では、プロビジョニング要求ごとに一意のアグリゲートセットがないかぎり、同時に複数の ONTAP をプロビジョニングすることはできません。
* IPv6経由でAstra Tridentを使用する場合は、と指定する必要があります `managementLIF` および `dataLIF` バックエンドの定義を角かっこで囲みます。例： ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``。
* を使用する場合 `solidfire-san` OpenShift 4.5を搭載したドライバ。基になるワーカーノードがMD5をCHAP認証アルゴリズムとして使用するようにします。




== 詳細については、こちらをご覧ください

* https://github.com/NetApp/trident["Astra Trident GitHub"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Astra Trident のブログ"^]

