---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator 
summary: 'Tridentオペレータは、の属性を使用して、Astra Tridentのインストール方法をカスタマイズできます `TridentOrchestrator` 仕様' 
---
= Trident オペレータの環境をカスタマイズ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Tridentオペレータが、の属性を使用して、Astra Tridentのインストール方法をカスタマイズできます `TridentOrchestrator` 仕様

属性のリストについては、次の表を参照してください。

[cols="3"]
|===
| パラメータ | 説明 | デフォルト 


| `namespace` | Astra Trident をインストールするネームスペース | デフォルト 


| `debug` | Astra Trident のデバッグを有効にします | いいえ 


| `IPv6` | IPv6 経由の Astra Trident をインストール | いいえ 


| `k8sTimeout` | Kubernetes 処理のタイムアウト | 30 秒 


| `silenceAutosupport` | AutoSupport バンドルをネットアップに自動的に送信しない | いいえ 


| `enableNodePrep` | ワーカーノードの依存関係を自動的に管理（ * beta * ） | いいえ 


| `autosupportImage` | AutoSupport テレメトリのコンテナイメージ | 「 NetApp/trident-autosupport ： 21.04.0 」 


| `autosupportProxy` | AutoSupport テレメトリを送信するプロキシのアドレス / ポート | "http://proxy.example.com:8888"[] 


| `uninstall` | Astra Trident のアンインストールに使用するフラグ | いいえ 


| `logFormat` | Astra Trident のログ形式が使用 [text 、 JSON] | テキスト（ Text ） 


| `tridentImage` | インストールする Astra Trident イメージ | 「 NetApp / Trident ： 21.04 」 


| `imageRegistry` | 形式の内部レジストリへのパス
`<registry FQDN>[:port][/subpath]` | "k83.gcr.io/sig-storage (k8s 1.17+) または Qua.io/k8scsi" 


| `kubeletDir` | ホスト上の kubelet ディレクトリへのパス | 「 /var/lib/kubelet 」 


| `wipeout` | Astra Trident を完全に削除するために削除するリソースのリスト |  


| `imagePullSecrets` | 内部レジストリからイメージをプルするシークレット |  
|===

IMPORTANT: `spec.namespace` は、で指定します `TridentOrchestrator` どのネームスペースAstra Tridentがにインストールされているかを示します。このパラメータ * は、 Astra Trident のインストール後に更新できません * 。これを実行すると、のステータスがになります `TridentOrchestrator` に変更します `Failed`。Astra Trident は、ネームスペース間での移行を意図したものではありません。


NOTE: 自動ワーカーノードの前処理は、非本番環境でのみ使用することを目的とした * ベータ機能です。

上記の属性は、を定義するときに使用できます `TridentOrchestrator` をクリックして、インストールをカスタマイズします。次に例を示します。

[listing]
----
$ cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  tridentImage: netapp/trident:21.04.0
  imagePullSecrets:
  - thisisasecret
----
インストールのカスタマイズを検討している場合は、それ以上にカスタマイズする必要があります `TridentOrchestrator` arguments allow、の使用を検討する必要があります `tridentctl` 必要に応じて変更できるカスタムYAMLマニフェストを生成します。
